M48
; DRILL file {KiCad 8.0.1} date 2024-05-07T10:14:04+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-07T10:14:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X87.122Y-58.166
X87.122Y-91.948
X161.011Y-57.937
X161.036Y-91.948
M30
